### ISSUE TITLE
Platypus option details

### ISSUE THREAD

**Issue by snewhouse** [andyrimmer/Platypus#39]
Hi
First off, we are having a lot of geeky fun with platypus - run times are amazing!
But, do you have some more detailed descriptions of what and how all the various option work?
And which option are the best go-to option for tweaking in order to change calling sensitivities?
Cheers
Steve

**Comment by dancooke** [comment]
Hi Steve,

Which options in particular are not clear (so I can edit the option help description)?

The main option for tweaking sensitivity is the ‘minPosterior’ option. The default value to 5 (phred scale), which is already pretty low, but you could try lowering this to 3 or 4 to increase sensitivity (at the expense of specificity).

You could also try the following to increase the number of candidates considered:

- Lowering ‘minReads’ option to 1 (default 2) could help with low coverage data.
- Lowering ‘minBaseQual’ will include more snp candidates.

If you’re looking at high complexity regions it may also be worth:

- Increasing ‘maxVariants’ option. This will increase the size of the haplotypes considered for calling, which is generally good for dealing with complex indels.
- Turning on the ‘mergeClusteredVariants’ option.

Best
Dan

On 30 Apr 2015, at 11:26, Stephen J Newhouse <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi
First off, we are having a lot of geeky fun with platypus - run times are amazing!
But, do you have some more detailed descriptions of what and how all the various option work?
And which option are the best go-to option for tweaking in order to change calling sensitivities?
Cheers
Steve

**Comment by snewhouse** [comment]
Hi

Thanks for the quick reply & tips, and sorry for the delay.

The things I'm not sure or clear on are the behaviour for things like:-

```
--maxGOF
--hapScoreThreshold
--maxHaplotypes
--scThreshold
```

When a variant or read/region falls below the values set by flags like these are they removed of just flagged?

If and when you get the time, please could you indicate what the defaults are, and if poss the settings you use on a regular basis for Exome v Whole Genome v Targeted ?

If some of this is documented, and I've missed it, then apologies - point me to the doc and I'll read it.. 

Cheers

Steve

**Comment by dancooke** [comment]
Hi Steve,

All the options related to VCF filter's (maxGOF, hapScoreThreshold, scThreshold) just changes the threshold for the filters to be applied; the calls aren't removed.

maxHaplotypes is an algorithm option that could affect calling - if set too low it's possible a true haplotype could be removed from the list of hypothetical haplotypes used to calculate genotype likelihoods. I'd leave this as it is unless calling is too slow (in which case decrease).

In terms of customising for specific data sets. I'd recommend starting with the defaults, and look to change things if calling sensitivity isn't as expected. We've tried to set up Platypus to work 'out of the box' as much as possible.

The defaults for all options should be available with --help.

Best
Dan
